#!/usr/bin/env bash

# Profile for a really bad connection (useful for testing the traffic shaping is working)
profile_desc="Really bad connectivity"
declare -A profile
profile["delay"]="300ms 100ms distribution normal"
profile["rate"]="512kbps buffer 128kb latency 10ms"
profile["loss"]="1%"