#!/usr/bin/env bash

# Profile for a good 3G connection
profile_desc="3G - good connectivity"
declare -A profile
profile["delay"]="100ms 90ms distribution normal"
profile["rate"]="850kbps buffer 512kb latency 1ms"
profile["loss"]="1%"