#!/usr/bin/env bash

# Profile for a lossy Edge connection
profile_desc="Edge - lossy connectivity"
declare -A profile
profile["delay"]="400ms 350ms distribution normal"
profile["rate"]="240kbps buffer 512kb latency 1ms"
profile["loss"]="1%"