#!/usr/bin/env bash

# Profile for a good wifi connection
profile_desc="Wifi - good connectivity"
declare -A profile
profile["delay"]="2ms 1ms distribution normal"
profile["rate"]="45mbps buffer 512kb latency 1ms"
profile["loss"]="0%"