#!/usr/bin/env bash

# Profile for a lossy wifi connection
profile_desc="Wifi - lossy connectivity"
declare -A profile
profile["delay"]="2ms 1ms distribution normal"
profile["rate"]="40mbps buffer 512kb latency 1ms"
profile["loss"]="1%"